//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from algol60.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Ialgol60Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class algol60BaseListener : Ialgol60Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.empty_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty_([NotNull] algol60Parser.Empty_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.empty_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty_([NotNull] algol60Parser.Empty_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] algol60Parser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] algol60Parser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] algol60Parser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] algol60Parser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] algol60Parser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] algol60Parser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.variable_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_identifier([NotNull] algol60Parser.Variable_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.variable_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_identifier([NotNull] algol60Parser.Variable_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_variable([NotNull] algol60Parser.Simple_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_variable([NotNull] algol60Parser.Simple_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscript_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscript_expression([NotNull] algol60Parser.Subscript_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscript_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscript_expression([NotNull] algol60Parser.Subscript_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscript_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscript_list([NotNull] algol60Parser.Subscript_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscript_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscript_list([NotNull] algol60Parser.Subscript_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_identifier([NotNull] algol60Parser.Array_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_identifier([NotNull] algol60Parser.Array_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscripted_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscripted_variable([NotNull] algol60Parser.Subscripted_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscripted_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscripted_variable([NotNull] algol60Parser.Subscripted_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] algol60Parser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] algol60Parser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_identifier([NotNull] algol60Parser.Procedure_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_identifier([NotNull] algol60Parser.Procedure_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.parameter_delimiter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_delimiter([NotNull] algol60Parser.Parameter_delimiterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.parameter_delimiter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_delimiter([NotNull] algol60Parser.Parameter_delimiterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual_parameter([NotNull] algol60Parser.Actual_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual_parameter([NotNull] algol60Parser.Actual_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual_parameter_list([NotNull] algol60Parser.Actual_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual_parameter_list([NotNull] algol60Parser.Actual_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.function_designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_designator([NotNull] algol60Parser.Function_designatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.function_designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_designator([NotNull] algol60Parser.Function_designatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.adding_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdding_operator([NotNull] algol60Parser.Adding_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.adding_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdding_operator([NotNull] algol60Parser.Adding_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.multiplying_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplying_operator([NotNull] algol60Parser.Multiplying_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.multiplying_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplying_operator([NotNull] algol60Parser.Multiplying_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] algol60Parser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] algol60Parser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] algol60Parser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] algol60Parser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] algol60Parser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] algol60Parser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_arithmetic_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_arithmetic_expression([NotNull] algol60Parser.Simple_arithmetic_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_arithmetic_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_arithmetic_expression([NotNull] algol60Parser.Simple_arithmetic_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_clause([NotNull] algol60Parser.If_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.if_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_clause([NotNull] algol60Parser.If_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.arithmetic_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmetic_expression([NotNull] algol60Parser.Arithmetic_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.arithmetic_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmetic_expression([NotNull] algol60Parser.Arithmetic_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelation([NotNull] algol60Parser.RelationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.relation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelation([NotNull] algol60Parser.RelationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_primary([NotNull] algol60Parser.Boolean_primaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_primary([NotNull] algol60Parser.Boolean_primaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_secondary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_secondary([NotNull] algol60Parser.Boolean_secondaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_secondary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_secondary([NotNull] algol60Parser.Boolean_secondaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_factor([NotNull] algol60Parser.Boolean_factorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_factor([NotNull] algol60Parser.Boolean_factorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_term([NotNull] algol60Parser.Boolean_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_term([NotNull] algol60Parser.Boolean_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.implication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplication([NotNull] algol60Parser.ImplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.implication"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplication([NotNull] algol60Parser.ImplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_boolean([NotNull] algol60Parser.Simple_booleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_boolean([NotNull] algol60Parser.Simple_booleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_expression([NotNull] algol60Parser.Boolean_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_expression([NotNull] algol60Parser.Boolean_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] algol60Parser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] algol60Parser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_identifier([NotNull] algol60Parser.Switch_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_identifier([NotNull] algol60Parser.Switch_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_designator([NotNull] algol60Parser.Switch_designatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_designator([NotNull] algol60Parser.Switch_designatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_designational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_designational_expression([NotNull] algol60Parser.Simple_designational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_designational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_designational_expression([NotNull] algol60Parser.Simple_designational_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.designational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignational_expression([NotNull] algol60Parser.Designational_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.designational_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignational_expression([NotNull] algol60Parser.Designational_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_basic_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnlabelled_basic_statement([NotNull] algol60Parser.Unlabelled_basic_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_basic_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnlabelled_basic_statement([NotNull] algol60Parser.Unlabelled_basic_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.basic_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasic_statement([NotNull] algol60Parser.Basic_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.basic_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasic_statement([NotNull] algol60Parser.Basic_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unconditional_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnconditional_statement([NotNull] algol60Parser.Unconditional_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unconditional_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnconditional_statement([NotNull] algol60Parser.Unconditional_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] algol60Parser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] algol60Parser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.compound_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_tail([NotNull] algol60Parser.Compound_tailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.compound_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_tail([NotNull] algol60Parser.Compound_tailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.block_head"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock_head([NotNull] algol60Parser.Block_headContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.block_head"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock_head([NotNull] algol60Parser.Block_headContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_compound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnlabelled_compound([NotNull] algol60Parser.Unlabelled_compoundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_compound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnlabelled_compound([NotNull] algol60Parser.Unlabelled_compoundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnlabelled_block([NotNull] algol60Parser.Unlabelled_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnlabelled_block([NotNull] algol60Parser.Unlabelled_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_statement([NotNull] algol60Parser.Compound_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_statement([NotNull] algol60Parser.Compound_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] algol60Parser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] algol60Parser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] algol60Parser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] algol60Parser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.destination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestination([NotNull] algol60Parser.DestinationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.destination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestination([NotNull] algol60Parser.DestinationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.left_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeft_part([NotNull] algol60Parser.Left_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.left_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeft_part([NotNull] algol60Parser.Left_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.left_part_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeft_part_list([NotNull] algol60Parser.Left_part_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.left_part_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeft_part_list([NotNull] algol60Parser.Left_part_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_statement([NotNull] algol60Parser.Assignment_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_statement([NotNull] algol60Parser.Assignment_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.go_to_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGo_to_statement([NotNull] algol60Parser.Go_to_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.go_to_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGo_to_statement([NotNull] algol60Parser.Go_to_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.dummy_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDummy_statement([NotNull] algol60Parser.Dummy_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.dummy_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDummy_statement([NotNull] algol60Parser.Dummy_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] algol60Parser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] algol60Parser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.conditional_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_statement([NotNull] algol60Parser.Conditional_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.conditional_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_statement([NotNull] algol60Parser.Conditional_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_list_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_list_element([NotNull] algol60Parser.For_list_elementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_list_element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_list_element([NotNull] algol60Parser.For_list_elementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_list([NotNull] algol60Parser.For_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_list([NotNull] algol60Parser.For_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_clause([NotNull] algol60Parser.For_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_clause([NotNull] algol60Parser.For_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_statement([NotNull] algol60Parser.For_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_statement([NotNull] algol60Parser.For_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActual_parameter_part([NotNull] algol60Parser.Actual_parameter_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActual_parameter_part([NotNull] algol60Parser.Actual_parameter_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_statement([NotNull] algol60Parser.Procedure_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_statement([NotNull] algol60Parser.Procedure_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] algol60Parser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] algol60Parser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] algol60Parser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] algol60Parser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_list([NotNull] algol60Parser.Type_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_list([NotNull] algol60Parser.Type_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] algol60Parser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] algol60Parser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.local_or_own"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocal_or_own([NotNull] algol60Parser.Local_or_ownContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.local_or_own"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocal_or_own([NotNull] algol60Parser.Local_or_ownContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_declaration([NotNull] algol60Parser.Type_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_declaration([NotNull] algol60Parser.Type_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.lower_bound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLower_bound([NotNull] algol60Parser.Lower_boundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.lower_bound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLower_bound([NotNull] algol60Parser.Lower_boundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.upper_bound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpper_bound([NotNull] algol60Parser.Upper_boundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.upper_bound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpper_bound([NotNull] algol60Parser.Upper_boundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.bound_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBound_pair([NotNull] algol60Parser.Bound_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.bound_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBound_pair([NotNull] algol60Parser.Bound_pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.bound_pair_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBound_pair_list([NotNull] algol60Parser.Bound_pair_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.bound_pair_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBound_pair_list([NotNull] algol60Parser.Bound_pair_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_segment([NotNull] algol60Parser.Array_segmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_segment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_segment([NotNull] algol60Parser.Array_segmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_list([NotNull] algol60Parser.Array_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_list([NotNull] algol60Parser.Array_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_declarer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_declarer([NotNull] algol60Parser.Array_declarerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_declarer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_declarer([NotNull] algol60Parser.Array_declarerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_declaration([NotNull] algol60Parser.Array_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_declaration([NotNull] algol60Parser.Array_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_list([NotNull] algol60Parser.Switch_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_list([NotNull] algol60Parser.Switch_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_declaration([NotNull] algol60Parser.Switch_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_declaration([NotNull] algol60Parser.Switch_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal_parameter([NotNull] algol60Parser.Formal_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal_parameter([NotNull] algol60Parser.Formal_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal_parameter_list([NotNull] algol60Parser.Formal_parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal_parameter_list([NotNull] algol60Parser.Formal_parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormal_parameter_part([NotNull] algol60Parser.Formal_parameter_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormal_parameter_part([NotNull] algol60Parser.Formal_parameter_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.identifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier_list([NotNull] algol60Parser.Identifier_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.identifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier_list([NotNull] algol60Parser.Identifier_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.value_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_part([NotNull] algol60Parser.Value_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.value_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_part([NotNull] algol60Parser.Value_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecifier([NotNull] algol60Parser.SpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecifier([NotNull] algol60Parser.SpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.specification_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecification_part([NotNull] algol60Parser.Specification_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.specification_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecification_part([NotNull] algol60Parser.Specification_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_heading([NotNull] algol60Parser.Procedure_headingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_heading([NotNull] algol60Parser.Procedure_headingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_body([NotNull] algol60Parser.Procedure_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_body([NotNull] algol60Parser.Procedure_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_declaration([NotNull] algol60Parser.Procedure_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_declaration([NotNull] algol60Parser.Procedure_declarationContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
