//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from algol60.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="algol60Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface Ialgol60Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.empty_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_([NotNull] algol60Parser.Empty_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.empty_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_([NotNull] algol60Parser.Empty_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] algol60Parser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] algol60Parser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] algol60Parser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] algol60Parser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] algol60Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] algol60Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_identifier([NotNull] algol60Parser.Variable_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_identifier([NotNull] algol60Parser.Variable_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_variable([NotNull] algol60Parser.Simple_variableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_variable([NotNull] algol60Parser.Simple_variableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscript_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_expression([NotNull] algol60Parser.Subscript_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscript_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_expression([NotNull] algol60Parser.Subscript_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscript_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_list([NotNull] algol60Parser.Subscript_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscript_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_list([NotNull] algol60Parser.Subscript_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_identifier([NotNull] algol60Parser.Array_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_identifier([NotNull] algol60Parser.Array_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.subscripted_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscripted_variable([NotNull] algol60Parser.Subscripted_variableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.subscripted_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscripted_variable([NotNull] algol60Parser.Subscripted_variableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] algol60Parser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] algol60Parser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_identifier([NotNull] algol60Parser.Procedure_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_identifier([NotNull] algol60Parser.Procedure_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.parameter_delimiter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_delimiter([NotNull] algol60Parser.Parameter_delimiterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.parameter_delimiter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_delimiter([NotNull] algol60Parser.Parameter_delimiterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActual_parameter([NotNull] algol60Parser.Actual_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActual_parameter([NotNull] algol60Parser.Actual_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActual_parameter_list([NotNull] algol60Parser.Actual_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActual_parameter_list([NotNull] algol60Parser.Actual_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.function_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_designator([NotNull] algol60Parser.Function_designatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.function_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_designator([NotNull] algol60Parser.Function_designatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.adding_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdding_operator([NotNull] algol60Parser.Adding_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.adding_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdding_operator([NotNull] algol60Parser.Adding_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.multiplying_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplying_operator([NotNull] algol60Parser.Multiplying_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.multiplying_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplying_operator([NotNull] algol60Parser.Multiplying_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] algol60Parser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] algol60Parser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] algol60Parser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] algol60Parser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] algol60Parser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] algol60Parser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_arithmetic_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_arithmetic_expression([NotNull] algol60Parser.Simple_arithmetic_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_arithmetic_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_arithmetic_expression([NotNull] algol60Parser.Simple_arithmetic_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_clause([NotNull] algol60Parser.If_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.if_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_clause([NotNull] algol60Parser.If_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.arithmetic_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmetic_expression([NotNull] algol60Parser.Arithmetic_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.arithmetic_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmetic_expression([NotNull] algol60Parser.Arithmetic_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelation([NotNull] algol60Parser.RelationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelation([NotNull] algol60Parser.RelationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_primary([NotNull] algol60Parser.Boolean_primaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_primary([NotNull] algol60Parser.Boolean_primaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_secondary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_secondary([NotNull] algol60Parser.Boolean_secondaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_secondary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_secondary([NotNull] algol60Parser.Boolean_secondaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_factor([NotNull] algol60Parser.Boolean_factorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_factor([NotNull] algol60Parser.Boolean_factorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_term([NotNull] algol60Parser.Boolean_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_term([NotNull] algol60Parser.Boolean_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.implication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplication([NotNull] algol60Parser.ImplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.implication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplication([NotNull] algol60Parser.ImplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_boolean([NotNull] algol60Parser.Simple_booleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_boolean([NotNull] algol60Parser.Simple_booleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.boolean_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean_expression([NotNull] algol60Parser.Boolean_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.boolean_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean_expression([NotNull] algol60Parser.Boolean_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] algol60Parser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] algol60Parser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_identifier([NotNull] algol60Parser.Switch_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_identifier([NotNull] algol60Parser.Switch_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_designator([NotNull] algol60Parser.Switch_designatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_designator([NotNull] algol60Parser.Switch_designatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.simple_designational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_designational_expression([NotNull] algol60Parser.Simple_designational_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.simple_designational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_designational_expression([NotNull] algol60Parser.Simple_designational_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.designational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignational_expression([NotNull] algol60Parser.Designational_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.designational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignational_expression([NotNull] algol60Parser.Designational_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_basic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlabelled_basic_statement([NotNull] algol60Parser.Unlabelled_basic_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_basic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlabelled_basic_statement([NotNull] algol60Parser.Unlabelled_basic_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.basic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasic_statement([NotNull] algol60Parser.Basic_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.basic_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasic_statement([NotNull] algol60Parser.Basic_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unconditional_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnconditional_statement([NotNull] algol60Parser.Unconditional_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unconditional_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnconditional_statement([NotNull] algol60Parser.Unconditional_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] algol60Parser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] algol60Parser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.compound_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_tail([NotNull] algol60Parser.Compound_tailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.compound_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_tail([NotNull] algol60Parser.Compound_tailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.block_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock_head([NotNull] algol60Parser.Block_headContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.block_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock_head([NotNull] algol60Parser.Block_headContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_compound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlabelled_compound([NotNull] algol60Parser.Unlabelled_compoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_compound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlabelled_compound([NotNull] algol60Parser.Unlabelled_compoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.unlabelled_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlabelled_block([NotNull] algol60Parser.Unlabelled_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.unlabelled_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlabelled_block([NotNull] algol60Parser.Unlabelled_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_statement([NotNull] algol60Parser.Compound_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_statement([NotNull] algol60Parser.Compound_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] algol60Parser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] algol60Parser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] algol60Parser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] algol60Parser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.destination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestination([NotNull] algol60Parser.DestinationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.destination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestination([NotNull] algol60Parser.DestinationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.left_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeft_part([NotNull] algol60Parser.Left_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.left_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeft_part([NotNull] algol60Parser.Left_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.left_part_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeft_part_list([NotNull] algol60Parser.Left_part_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.left_part_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeft_part_list([NotNull] algol60Parser.Left_part_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_statement([NotNull] algol60Parser.Assignment_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_statement([NotNull] algol60Parser.Assignment_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.go_to_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGo_to_statement([NotNull] algol60Parser.Go_to_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.go_to_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGo_to_statement([NotNull] algol60Parser.Go_to_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.dummy_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDummy_statement([NotNull] algol60Parser.Dummy_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.dummy_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDummy_statement([NotNull] algol60Parser.Dummy_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] algol60Parser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] algol60Parser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.conditional_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_statement([NotNull] algol60Parser.Conditional_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.conditional_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_statement([NotNull] algol60Parser.Conditional_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_list_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_list_element([NotNull] algol60Parser.For_list_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_list_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_list_element([NotNull] algol60Parser.For_list_elementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_list([NotNull] algol60Parser.For_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_list([NotNull] algol60Parser.For_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_clause([NotNull] algol60Parser.For_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_clause([NotNull] algol60Parser.For_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_statement([NotNull] algol60Parser.For_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_statement([NotNull] algol60Parser.For_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.actual_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActual_parameter_part([NotNull] algol60Parser.Actual_parameter_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.actual_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActual_parameter_part([NotNull] algol60Parser.Actual_parameter_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_statement([NotNull] algol60Parser.Procedure_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_statement([NotNull] algol60Parser.Procedure_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] algol60Parser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] algol60Parser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] algol60Parser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] algol60Parser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_list([NotNull] algol60Parser.Type_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_list([NotNull] algol60Parser.Type_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_([NotNull] algol60Parser.Type_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_([NotNull] algol60Parser.Type_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.local_or_own"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocal_or_own([NotNull] algol60Parser.Local_or_ownContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.local_or_own"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocal_or_own([NotNull] algol60Parser.Local_or_ownContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_declaration([NotNull] algol60Parser.Type_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_declaration([NotNull] algol60Parser.Type_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.lower_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLower_bound([NotNull] algol60Parser.Lower_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.lower_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLower_bound([NotNull] algol60Parser.Lower_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.upper_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpper_bound([NotNull] algol60Parser.Upper_boundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.upper_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpper_bound([NotNull] algol60Parser.Upper_boundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.bound_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBound_pair([NotNull] algol60Parser.Bound_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.bound_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBound_pair([NotNull] algol60Parser.Bound_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.bound_pair_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBound_pair_list([NotNull] algol60Parser.Bound_pair_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.bound_pair_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBound_pair_list([NotNull] algol60Parser.Bound_pair_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_segment([NotNull] algol60Parser.Array_segmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_segment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_segment([NotNull] algol60Parser.Array_segmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_list([NotNull] algol60Parser.Array_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_list([NotNull] algol60Parser.Array_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_declarer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_declarer([NotNull] algol60Parser.Array_declarerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_declarer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_declarer([NotNull] algol60Parser.Array_declarerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.array_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_declaration([NotNull] algol60Parser.Array_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.array_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_declaration([NotNull] algol60Parser.Array_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_list([NotNull] algol60Parser.Switch_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_list([NotNull] algol60Parser.Switch_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.switch_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_declaration([NotNull] algol60Parser.Switch_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.switch_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_declaration([NotNull] algol60Parser.Switch_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_parameter([NotNull] algol60Parser.Formal_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_parameter([NotNull] algol60Parser.Formal_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_parameter_list([NotNull] algol60Parser.Formal_parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_parameter_list([NotNull] algol60Parser.Formal_parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.formal_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormal_parameter_part([NotNull] algol60Parser.Formal_parameter_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.formal_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormal_parameter_part([NotNull] algol60Parser.Formal_parameter_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier_list([NotNull] algol60Parser.Identifier_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier_list([NotNull] algol60Parser.Identifier_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.value_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_part([NotNull] algol60Parser.Value_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.value_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_part([NotNull] algol60Parser.Value_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecifier([NotNull] algol60Parser.SpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecifier([NotNull] algol60Parser.SpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.specification_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecification_part([NotNull] algol60Parser.Specification_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.specification_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecification_part([NotNull] algol60Parser.Specification_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_heading([NotNull] algol60Parser.Procedure_headingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_heading([NotNull] algol60Parser.Procedure_headingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_body([NotNull] algol60Parser.Procedure_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_body([NotNull] algol60Parser.Procedure_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="algol60Parser.procedure_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_declaration([NotNull] algol60Parser.Procedure_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="algol60Parser.procedure_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_declaration([NotNull] algol60Parser.Procedure_declarationContext context);
}
