//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ex.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IExListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterP([NotNull] ExParser.PContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExParser.p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitP([NotNull] ExParser.PContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] ExParser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] ExParser.SContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExParser.m"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterM([NotNull] ExParser.MContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExParser.m"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitM([NotNull] ExParser.MContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT([NotNull] ExParser.TContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT([NotNull] ExParser.TContext context);
}
